#!/bin/bash
# Compile the Python file
python3 -m py_compile "$PYFILE"

# Rename the compiled file to the desired output format
compiled_file="${PYFILE}c"
mv "${PYFILE/__pycache__/*}.pyc" "$compiled_file"

